import os
import uuid
import shutil
import subprocess
import tempfile
import gurobipy as gp
from utils.gcg_dec_parser import constraint_permutation_from_dec
from core.problem_transform.problem_permutator import ProblemPermutator

def rename_gp_file(output_dir: str, base_name: str) -> str:
    """Finds the first .gp file in output_dir and renames it to include the base_name."""
    gp_files = [f for f in os.listdir(output_dir) if f.endswith('.gp')]
    if not gp_files:
        raise FileNotFoundError("No GCG-generated .gp file found")
    original_gp = os.path.join(output_dir, gp_files[0])
    new_gp = os.path.join(output_dir, f"{base_name}_decomposition.gp")
    os.rename(original_gp, new_gp)
    return new_gp

def run_gnuplot_on_gp(gp_file: str, output_dir: str) -> None:
    """Runs gnuplot on the given gp_file."""
    subprocess.run(["gnuplot", gp_file], cwd=output_dir, check=True)

def rename_generated_pdf(output_dir: str, base_name: str) -> str:
    """
    Finds the auto-generated PDF (which starts with '_MPS_') and renames it
    to include the base_name. Returns the final PDF file path.
    """
    pdf_files = [f for f in os.listdir(output_dir)
                 if f.endswith('.pdf') and f.startswith('_MPS_')]
    if pdf_files:
        original_pdf = os.path.join(output_dir, pdf_files[0])
        final_pdf = os.path.join(output_dir, f"{base_name}_decomposition.pdf")
        os.rename(original_pdf, final_pdf)
        print(f"✓ PDF visualization saved to {final_pdf}")
        return final_pdf
    else:
        print("Warning: No PDF output was generated")
        return None

def cleanup_visualization_temp_files(output_dir: str, base_name: str) -> None:
    """Removes temporary files generated during visualization."""
    # Remove the cleaned gp file if it exists.
    gp_file = os.path.join(output_dir, f"{base_name}_decomposition.gp")
    if os.path.exists(gp_file):
        os.remove(gp_file)
    # Remove any remaining GCG-generated plot files.
    for f in os.listdir(output_dir):
        if f.startswith('_MPS_') and (f.endswith('.eps') or f.endswith('.gp')):
            try:
                os.remove(os.path.join(output_dir, f))
            except Exception as e:
                print(f"Warning: Could not remove temporary file {f}: {str(e)}")

def process_gp_file(output_dir: str, base_name: str) -> None:
    """
    Processes the .gp file generated by GCG:
    
    1. Renames the .gp file to a more meaningful name.
    2. Runs gnuplot on the cleaned .gp file to generate a PDF.
    3. Renames the auto-generated PDF.
    4. Copies the final PDF to a permanent directory computed from the OS.
    5. Cleans up temporary files.
    
    The permanent directory is computed as:
        os.path.join(os.getcwd(), "viz")
    """
    try:
        # Step 1: Rename the GP file.
        clean_gp = rename_gp_file(output_dir, base_name)
        
        # Step 2: Run gnuplot to generate visualization.
        run_gnuplot_on_gp(clean_gp, output_dir)
        
        # Step 3: Rename the generated PDF and get its path.
        final_pdf = rename_generated_pdf(output_dir, base_name)
        
        # Step 4: Compute the permanent visualization folder from the OS.
        permanent_viz_folder = os.path.join(os.getcwd(), "viz")
        os.makedirs(permanent_viz_folder, exist_ok=True)
        
        # Copy the final PDF to the permanent directory.
        if final_pdf:
            dest_file = os.path.join(permanent_viz_folder, os.path.basename(final_pdf))
            shutil.copy2(final_pdf, dest_file)
            print(f"✓ Visualization copied to {dest_file}")
    
    except Exception as e:
        print(f"Error processing visualization: {str(e)}")
        raise
    finally:
        # Step 5: Clean up temporary visualization files.
        cleanup_visualization_temp_files(output_dir, base_name)

def generate_unique_id() -> str:
    return uuid.uuid4().hex[:8]

def create_cmd_file(temp_input: str, output_dir: str, unique_id: str) -> str:
    cmd_file = os.path.join(output_dir, f"cmds_{unique_id}.cmd")
    with open(cmd_file, 'w') as f:
        f.write(f'read "{temp_input}"\n')
        f.write('set detection enabled TRUE\n')
        f.write('detect\n')
        f.write('explore\n')
        f.write('select 0\n')
        f.write('export 0\n')
        f.write('quit\n')
        f.write(f'write selected "{output_dir}" dec\n')
        f.write('quit\n')
    return cmd_file

def run_gcg(cmd_file: str, output_dir: str, timeout: int = 300):
    subprocess.run(
        ["gcg", "-b", cmd_file],
        cwd=output_dir,
        check=True,
        timeout=timeout
    )

def find_latest_dec_file(output_dir: str) -> str:
    dec_files = [f for f in os.listdir(output_dir) if f.endswith('.dec')]
    if not dec_files:
        raise FileNotFoundError("GCG did not produce a .dec file.")
    dec_files = sorted(dec_files, key=lambda f: os.path.getctime(os.path.join(output_dir, f)), reverse=True)
    return os.path.join(output_dir, dec_files[0])

def preprocess_with_gcg(model, gp_env):
    """
    Preprocesses the model using GCG entirely in-memory while visualizing the GP file.
    The final visualization PDF is saved in a permanent folder computed as:
        os.path.join(os.getcwd(), "viz")
    """
    unique_id = generate_unique_id()
    
    # Use a temporary directory that automatically cleans up.
    with tempfile.TemporaryDirectory() as tmp_dir:
        temp_input = os.path.join(tmp_dir, f"temp_input_{unique_id}.mps")
        
        # Write the original model to a temporary file for GCG to process.
        model.write(temp_input)
        
        # Create the command file for GCG.
        cmd_file = create_cmd_file(temp_input, tmp_dir, unique_id)
        
        # Run GCG.
        run_gcg(cmd_file, tmp_dir)
        
        # Visualize the GP file.
        base_name = os.path.splitext(os.path.basename(temp_input))[0]
        process_gp_file(tmp_dir, base_name)
        
        # Locate the generated .dec file.
        dec_file_path = find_latest_dec_file(tmp_dir)
        
        # Load the original model from the temporary file.
        original_model = gp.read(temp_input)
        
        # Compute the constraint permutation using the dec file.
        constr_perm = constraint_permutation_from_dec(original_model, dec_file_path)
        return constr_perm
    
        # Apply the permutation.
        perm_util = ProblemPermutator(gp_env=gp_env, original_model=original_model)
        permuted_model, _ = perm_util.apply_dec_permutation(original_model, constr_perm)
        
        # Return the permuted model in memory.
        return permuted_model

